name: "[nitrodigest] Publish to PyPI"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Where to publish (testpypi or pypi)"
        required: true
        default: "testpypi"
        type: choice
        options:
          - testpypi
          - pypi

defaults:
  run:
    working-directory: Projects/Nitrodigest/Cli

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to ${{ inputs.environment }}
        uses: pypa/gh-action-pypi-publish@release/v1

        with:
          repository-url: ${{ inputs.environment == 'pypi' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
          packages-dir: Projects/Nitrodigest/Cli/dist/
