name: Generate and Test RSS Feed

on:
  push:
    branches:
      - main
    paths:
      - 'website/**/*.md'
      - 'website/**/*.js'
      - 'website/**/*.json'

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: website/package.json

      - name: Install dependencies
        working-directory: ./website
        run: npm install

      - name: Generate RSS feed
        working-directory: ./website
        run: node feed.xml.js

      - name: Run unit tests
        working-directory: ./website
        run: npm run test:unit

      - name: Install Playwright browsers
        working-directory: ./website
        run: npx playwright install --with-deps

      - name: Run e2e tests
        working-directory: ./website
        run: npm run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            website/playwright-report/
            website/test-results/
          retention-days: 30

      - name: Deploy to Cloudflare Pages
        if: success()
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy website/public --project-name=frodigo-rss